{{- if .Values.admissionWebhook.enabled -}}
{{- $tls := include "freqtrade-operator-webhook.tls" . | fromYaml -}}
{{- $ca := .Values.admissionWebhook.tls.caBundle | default $tls.ca -}}
{{- if not .Values.admissionWebhook.tls.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freqtrade-operator-webhook.fullname" . }}-tls
  labels:
    {{- include "freqtrade-operator-webhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: kubernetes.io/tls
data:
  tls.crt: {{ $tls.cert | b64enc }}
  tls.key: {{ $tls.key | b64enc }}
  ca.crt: {{ $ca | b64enc }}
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "freqtrade-operator-webhook.fullname" . }}-validate-bot
webhooks:
- name: validate-bot.{{ include "freqtrade-operator-webhook.fullname" . }}.{{ .Release.Namespace }}.svc
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "freqtrade-operator-webhook.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: "/admission/freqtrade.io/bot/validate"
      port: {{ .Values.admissionWebhook.port }}
    caBundle: {{ $ca | b64enc }}
  rules:
  - apiGroups: ["freqtrade.io"]
    apiVersions: ["v1alpha1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["bots"]
    scope: "Namespaced"
{{- end }}