name: default

on:
  push:
    branches-ignore:
      - main
      - dev
    tags-ignore:
      - '**'

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: "3.43.3"

      - name: Lint commit message
        run: |
          pip install gitlint
          git log -1 --pretty=%B | gitlint

      - name: Lint code
        run: task rust:lint
